import { NextResponse } from 'next/server'

// Add the slug of any permanently deleted blog post to this array.
// A 410 Gone response tells Google the page is permanently removed,
// which results in faster deindexing than a plain 404.
//
// Format: the slug only, no leading slash, no /blog/ prefix.
// Example: 'my-old-post-title'
//
// Once Google has deindexed the URL (confirm in Google Search Console),
// you can remove the slug from this list.
const DELETED_POST_SLUGS = [
	'github-automated-security-fixes-beta',
	'github-integration-app-smart-commits-on-jira',
	'how-i-upgraded-my-nextjs-13-blog-to-nextjs-14',
	'how-to-remove-an-unwanted-local-repository-in-sourcetree-with-command-line',
	'eslint-parsing-in-react',
	'firefox-0-day-flaw-update',
	'fixing-your-nvm-install',
	'flexbox-sticky-footer-and-react',
	'a-new-react-workflow-with-react-166-and-webpack-4',
	'connecting-to-mongodb-compass-to-access-local-mongodb-databases-via-the-new-mongosh-shell',
	'does-ai-have-ethics',
	'es2018-language-features-available-in-v8js-v64-and-chrome-64',
	'how-to-create-copy-link-with-highlight-links',
	'my-experience-updating-my-nextjs-business-site-to-fix-npm-packages',
	'mastering-javascript',
	'installing-visual-studio-code-text-editor-on-a-mac',
	'im-now-on-patreon',
	'how-to-create-a-sticky-footer-when-you-originally-didnt-account-for-having-one',
	'how-and-why-i-came-to-dropping-off-my-macbook-pro-with-super-computer-doctor-in-murray-hill',
	'how-challenges-road-blocks-and-mistakes-can-lead-to-fruitful-progress-as-a-web-designer-or-developer',
	'guess-the-keys-app',
	'getting-started-with-nextjs',
	'audio-visual-slider',
	'canvas-2d-breakout-game',
	'chattr-public-and-private-realtime-chat',
	'dragging-bubbles-app',
	'guess-the-keys',
	'making-music-in-the-browser',
	'monsters-api-js-app',
	'monsters-rolodex-react-hooks',
	'omdb-api-js-app',
	'omdb-api-nextjs',
	'poke-api-web-app',
	'reinstalling-homebrew-on-macbook-pro-silicon-2021',
	'rockin-synth',
	'the-cat-whisperer',
	'trump-talks',
	'web-audio-api-ajax',
	'welcome-to-the-groove',
	'wikipedia-viewer',
	'adding-host-property-to-webpack-config',
	'apis-for-developers-and-what-pitfalls-to-watch-out-for',
	'class-conflicts',
	'connecting-your-iphone-hotspot-to-your-macbook-pro-ventura-os',
	'converting-image-formats-on-macos-using-the-finder-app',
	'creating-a-custom-html5-video-player-and-the-shadow-dom',
	'creating-a-shell-script-from-an-applescript-targeting-the-macos-music-app',
	'creating-an-applescript-that-plays-an-album-in-the-macos-music-app',
	'custom-html5-video-player',
	'data-recovery-with-git',
	'deploying-to-gh-pages-with-git-subtree',
	'dont-name-any-of-your-project-directories-functions',
	'downloading-a-pdf-file-from-the-internet-using-command-line-on-your-mac',
	'enabling-content-insertion-inside-the-vim-editor-on-macos-when-skipping-the-insert-command',
	'enabling-the-auto-complete-feature-in-git-with-z-shell',
	'error-hydration-failed-because-the-initial-ui-does-not-match-what-was-rendered-on-the-server-in-nextjs',
	'fixing-mdx-linting-errors-in-nextjs-using-eslint-plugin-mdx',
	'fixing-the-path-to-xcode-after-installing-latest-version-on-macos-monterey',
	'forking-a-repository-on-github-and-subsequently-creating-a-pull-request',
	'git-large-file-storage',
	'hosting-my-full-stack-react-nodejs-socketio-application-on-heroku',
	'how-to-create-new-lines-inside-text-prop-values-in-nextjs-and-javascript-in-general',
	'how-to-determine-whether-your-xcode-installupgrade-has-been-successful-or-not',
	'how-to-enable-async-await-in-a-nodejsexpress',
	'how-to-import-mychart-appointments-into-the-macos-calendar-app',
	'how-to-find-out-the-latest-nodejs-lts-version-via-command-line',
	'how-to-prevent-buttons-from-moving-on-click',
	'how-to-properly-configure-husky-pre-commits-with-lint-staged',
	'how-to-save-terminal-output-to-a-file-for-future-reference',
	'how-to-set-up-more-than-one-wireless-printer-with-hp-eprint-using-the-hp-smart-app',
	'how-to-show-hidden-files-in-windows-11',
	'how-to-show-hidden-files-or-folders-on-macos',
	'how-to-take-a-screenshot-on-your-mac-mojave-or-later',
	'how-to-uninstall-postgresql-on-osx-and-reinstall-with-homebrew',
	'how-to-uninstall-vs-code-seamlessly-on-your-mac',
	'blog/html5-canvas-game-development',
	'i-gave-my-first-presentation-tonight',
	'image-lazy-loading-with-vanilla-javascript',
	'implementing-es6-modules-without-webpack-or-babel',
	'importing-images-in-react-20-jest-and-babel-7',
	'importing-images-in-react',
	'installing-pgadmin-only-after-installing-postgresql-with-homebrew-part-2',
	'installing-pgadmin-only-after-installing-postgresql-with-homebrew',
	'installing-python-380-on-your-mac-with-pyenv',
	'installing-the-latest-version-of-mongodb-on-macos-monterey',
	'installing-the-latest-version-of-python-on-mac-os-catalina-and-overriding-the-old-default-pre-installed-version',
	'ipad-vs-traditional-radio-or-stereo',
	'jest-react-and-mocks',
	'making-the-git-pre-commit-hook-work-on-macos',
	'mongodb-compass-vs-robo-3t-vs-local-mongo-shell',
	'multer-amazon-s3-and-aws-amplify',
	'my-amazon-s3-moment',
	'my-first-time-using-react-16',
	'my-updated-custom-react-workflow-2nd-edition-is-here',
	'nodejs-and-graphql',
	'opening-up-iterm2-via-spotlight-search-on-your-mac',
	'outdated-content-and-google-custom-search',
	'outdated-javascript-tooling-vulnerabilities-and-security',
	'playing-a-single-song-in-the-music-app-using-applescript',
	'postgresql-and-the-osx-migration-assistant',
	'react-workflows-update-1',
	'refactoring-your-js-workflow-when-your-images-are-in-your-css-only',
	'removing-caps-from-css-headings',
	'requestanimationframe-and-polyfill-in-reactjs',
	'reverting-a-file-to-a-specific-revision-in-git',
	'reverting-a-particular-committed-file-to-a-previous-version-in-git',
	'safari-web-inspector-vs-chrome-developer-tools-vs-firefox-browser-tools',
	'sharing-images-on-tumblr',
	'sticky-footers-in-the-age-of-coronavirus',
	'successfully-using-live-share-extension-in-vs-code',
	'switching-shells-on-macos-catalina',
	'the-apple-dictation-and-text-editors-bug',
	'the-babel-7-config',
	'the-browser-war-chrome-vs-firefox',
	'the-chrome-favicon-nightmare-and-how-i-finally-fixed-it',
	'the-emerging-new-balance-of-power',
	'the-importance-of-adapting-to-change-quickly',
	'the-importance-of-eslint-and-react',
	'the-importance-of-taking-time-out-to-check-your-code-and-html-markup',
	'the-jest-side-effect',
	'the-new-https-authentication-to-github',
	'the-new-mongodb-shell-mongosh',
	'the-new-npm-audit-with-6-npm',
	'the-new-world-do-it-yourself-diy',
	'the-real-reason-behind-why-vscode-seemed-to-go-haywire-on-me',
	'the-really-cool-jscolor-color-picker',
	'the-say-command-in-osx-command-line',
	'the-sticky-footer-and-nextjs-13',
	'to-npm-trash-or-not-to-npm-trash',
	'understanding-the-github-ssh-mistake-fix-and-how-it-would-have-affected-me-if-i-hadnt-been-able-to-fix-it',
	'upgrading-postgresql-from-version-104-to-111-via-homebrew-osx',
	'using-google-meet-for-on-the-fly-screen-sharing',
	'using-node-sass-instead-of-system-sass-in-macos-catalina',
	'using-post-request-with-vs-codes-rest-client',
	'using-umask-to-change-default-permissions-in-linux-and-unix-macos',
	'using-vs-codes-rest-client-extension-instead-of-postman',
	'vs-code-and-the-live-server-extension',
	'vscodium-instead-of-vscode',
	'warp-terminal-with-built-in-ai-essentials-in-macos',
	'what-happens-when-you-edit-a-twitter-tweet',
	'what-to-do-when-you-cant-upgrade-oh-my-zsh',
	'when-an-object-property-key-is-a-string-in-javascript',
	'when-and-why-it-is-important-to-refactor-code',
	'when-the-homebrew-command-brew-update-fails',
	'why-being-able-to-use-dotenv-with-nextjs-is-so-huge',
	'why-i-chose-plausible-analytics-with-my-nextjs-site',
	'why-i-fell-in-love-with-vs-codes-live-share-and-why-you-should-too',
	'why-increasing-your-technological-intelligence-is-important',
	'changing-mac-default-screenshot-file-format-to-jpg',
	'add-husky-to-s-subfolder-of-a-git-root-repository',
	'how-to-add-files-to-your-gitignore-with-no-sweat',
	'data/blog/add-husky-to-a-subfolder-of-a-git-root-repository.mdx',
	'data/blog/adding-husky-to-your-development-workflow.mdx',
	'data/blog/changing-your-homebrew-postgresql-configuration-from-trust-to-md5.mdx',
	'data/blog/creating-react-boilerplate-code-in-vs-code.mdx',
	'data/blog/git-instaweb-and-local-git-commits.mdx',
	'data/blog/how-itunes-match-saved-me-from-losing-itunes-purchases-bought-under-previous-apple-ids.mdx',
	'data/blog/how-to-completely-remove-cached-ip-addresses.mdx',
	'data/blog/how-to-copy-a-directory-from-command-line.mdx',
	'data/blog/how-to-find-a-folder-on-your-computer.mdx',
	'data/blog/how-to-unsend-a-gmail-email.mdx',
	'data/blog/how-to-upgrade-all-the-packages-in-your-django-application-in-one-fell-swoop.mdx',
	'data/blog/introduction-to-command-prompt-commands-in-windows-11.mdx',
	'data/blog/narrowly-escaping-the-need-to-remove-giscus.mdx',
	'data/blog/creating-css-grids-without-the-need-for-media-queries.mdx',
	'data/blog/applying-how-i-created-a-figure-element-component-to-creating-a-static-text-tweet-component.mdx',
	'data/blog/renaming-your-remote-github-repository.mdx',
	'data/blog/the-importance-of-updates-and-why-they-are-important-in-cybersecurity.mdx',
	'data/blog/updating-the-node-architecture-on-macbook-pro-silicon.mdx',
	'data/blog/when-a-bare-bones-automated-js-workflow-makes-sense.mdx',
	'data/blog/windows-cmd-basics-and-commands-by-example.mdx',
]

export function middleware(request) {
	const { pathname } = request.nextUrl

	// Only intercept /blog/* routes
	if (pathname.startsWith('/blog/')) {
		const slug = pathname.replace('/blog/', '').replace(/\/$/, '')

		if (DELETED_POST_SLUGS.includes(slug)) {
			return new NextResponse(null, {
				status: 410,
				statusText: 'Gone',
			})
		}
	}

	return NextResponse.next()
}

export const config = {
	matcher: ['/blog/:slug*'],
}
