export { default as Dev } from './Dev'
export { default as Email } from './Email'
export { default as Github } from './Github'
export { default as Linkedin } from './Linkedin'
export { default as Patreon } from './Patreon'
export { default as Sitemap } from './Sitemap'
export { default as Tumblr } from './Tumblr'
export { default as Twitter } from './Twitter'
